version: '2'
services:
  mindforme-app:
    image: mindforme
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mindforme-mariadb:3306/mindforme?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://mindforme-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mindforme-elasticsearch:9200
    ports:
      - 8080:8080
  mindforme-mariadb:
    extends:
      file: mariadb.yml
      service: mindforme-mariadb
  mindforme-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mindforme-elasticsearch
