export const enum NotificationType {
  ACCEPT_FRIEND = 'ACCEPT_FRIEND',

  REMOVE_FRIEND = 'REMOVE_FRIEND',

  CANCEL_FRIEND = 'CANCEL_FRIEND',

  REJECT_FRIEND = 'REJECT_FRIEND',

  CREATE_HELPING = 'CREATE_HELPING',

  ACCEPT_HELPING = 'ACCEPT_HELPING',

  CONFIRM_HELPING = 'CONFIRM_HELPING',

  DECLINE_HELPING = 'DECLINE_HELPING',

  COMPLETE_HELPING = 'COMPLETE_HELPING',

  REVIEW_HELPING = 'REVIEW_HELPING',

  NEW_FRIEND = 'NEW_FRIEND',

  RENEW_SUBSCRIPTION = 'RENEW_SUBSCRIPTION',

  EXPIRED_SUBSCRIPTION = 'EXPIRED_SUBSCRIPTION',
}
